// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project_3

#ifndef _SQUARELINE_PROJECT_3_UI_H
#define _SQUARELINE_PROJECT_3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Image4;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_ImgButton8;
extern lv_obj_t * ui_ImgButton9;
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_ImgButton5;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_rectangle_11_png);    // assets\Rectangle 11.png
LV_IMG_DECLARE(ui_img_764727584);    // assets\light-01.png
LV_IMG_DECLARE(ui_img_group_154_png);    // assets\Group 154.png
LV_IMG_DECLARE(ui_img_731799194);    // assets\veevo-conn-logo 4.png
LV_IMG_DECLARE(ui_img_1648071431);    // assets\ligh-04.png
LV_IMG_DECLARE(ui_img_483437507);    // assets\ligh-02.png
LV_IMG_DECLARE(ui_img_1565166686);    // assets\ligh-05.png
LV_IMG_DECLARE(ui_img_2001718481);    // assets\ligh-06.png
LV_IMG_DECLARE(ui_img_244644622);    // assets\ligh-01.png
LV_IMG_DECLARE(ui_img_598291672);    // assets\ligh-03.png
LV_IMG_DECLARE(ui_img_group_59_png);    // assets\Group 59.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
