// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project_3

#include "ui.h"

void ui_comp_Panelgroup_create_hook(lv_obj_t * comp)
{
}
