// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project_3

#ifndef _UI_COMP_PANELGROUP_H
#define _UI_COMP_PANELGROUP_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panelgroup
#define UI_COMP_PANELGROUP_PANELGROUP 0
#define UI_COMP_PANELGROUP_UPDATETIMESWITCH 1
#define UI_COMP_PANELGROUP_UPDATETIMELABEL 2
#define _UI_COMP_PANELGROUP_NUM 3
lv_obj_t * ui_Panelgroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
