// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: SquareLine_Project_3

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image6, &ui_img_rectangle_11_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_Image6, 1);
    lv_obj_set_y(ui_Image6, 7);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton6 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1648071431, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_group_154_png, NULL);
    lv_obj_set_width(ui_ImgButton6, 168);
    lv_obj_set_height(ui_ImgButton6, 140);
    lv_obj_set_x(ui_ImgButton6, -247);
    lv_obj_set_y(ui_ImgButton6, 125);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButton6, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_ImgButton7 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_483437507, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_group_154_png, NULL);
    lv_obj_set_width(ui_ImgButton7, 168);
    lv_obj_set_height(ui_ImgButton7, 140);
    lv_obj_set_x(ui_ImgButton7, 0);
    lv_obj_set_y(ui_ImgButton7, -53);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButton7, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_ImgButton8 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1565166686, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_group_154_png, NULL);
    lv_obj_set_width(ui_ImgButton8, 168);
    lv_obj_set_height(ui_ImgButton8, 140);
    lv_obj_set_x(ui_ImgButton8, 0);
    lv_obj_set_y(ui_ImgButton8, 125);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButton8, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_ImgButton9 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2001718481, NULL);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_group_154_png, NULL);
    lv_obj_set_width(ui_ImgButton9, 168);
    lv_obj_set_height(ui_ImgButton9, 140);
    lv_obj_set_x(ui_ImgButton9, 247);
    lv_obj_set_y(ui_ImgButton9, 125);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButton9, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_ImgButton4 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_244644622, NULL);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_group_154_png, NULL);
    
    lv_obj_set_width(ui_ImgButton4, 168);
    lv_obj_set_height(ui_ImgButton4, 140);
    lv_obj_set_x(ui_ImgButton4, -247);
    lv_obj_set_y(ui_ImgButton4, -53);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButton4, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_ImgButton5 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_598291672, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_group_154_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_group_154_png, NULL);
    lv_obj_set_width(ui_ImgButton5, 168);
    lv_obj_set_height(ui_ImgButton5, 140);
    lv_obj_set_x(ui_ImgButton5, 247);
    lv_obj_set_y(ui_ImgButton5, -53);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButton5, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 242);
    lv_obj_set_height(ui_Button2, 74);
    lv_obj_set_x(ui_Button2, -236);
    lv_obj_set_y(ui_Button2, -183);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button2, &ui_img_731799194, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    // lv_obj_set_event_cb(ui_ImgButton4, event_handler);

}
